@isTest
private class ProjectRESTServiceTest {
  //Implement Apex REST service tests here
  
  /*
  public with sharing class DateFormatterTest {
@isTest
public static void testGetFormattedDate(){
    //Create a mock version of the DateHelper class
    fflib_ApexMocks mocks = new fflib_ApexMocks();
    DateHelper mockDH = (DateHelper) mocks.factory(DateHelper.class);
    DateFormatter df =  new DateFormatter();
    mocks.startStubbing();
    mocks.when(mockDH.getTodaysDate()).thenReturn('8/8/2016');
    mocks.stopStubbing();
 
    //Use the mocked object in the test
    system.assertEquals('Today\'s date is 8/8/2016',df.getFormattedDate(mockDH));
}
 
}
*/
}